version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      # - SPLUNK_LICENSE_URI=/tmp/license/splunk.lic
      - SPLUNK_PASSWORD='PASSword123!@#'
    ports:
      - 8000:8000
      - 8089:8089
      - 8088:8088
    volumes:
      - ./default.yml:/tmp/defaults/default.yml
      #   - ./splunk.lic:/tmp/license/splunk.lic
